{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "landing.fullname" . }}
  labels:
    {{- include "landing.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ default .Values.hostname .Values.istio.virtualservice.host | quote }}
  gateways:
  - {{ default (include "landing.fullname" .) .Values.istio.virtualservice.gateway }}
  http:
  - match:
    - uri:
        prefix: {{ tpl .Values.istio.virtualservice.prefix $ }}
    {{- if .Values.istio.virtualservice.rewriteUri }}
    rewrite:
      uri: {{ tpl .Values.istio.virtualservice.rewriteUri $ }}
    {{- end }}
    route:
    - destination:
        host: {{ tpl .Values.istio.virtualservice.destination $ }}
        port:
          number: {{ tpl .Values.istio.virtualservice.destinationPort $ }}
{{- end }}
{{- end }}
